CREATE TABLE IF NOT EXISTS `daftar_ulang_ird` (
  `no_register` varchar(10) NOT NULL,
  `no_medrec` varchar(10) DEFAULT NULL,
  `tgl_kunjungan` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ublnrj` int(11) DEFAULT '0',
  `uharirj` int(11) DEFAULT '0',
  `umurrj` int(11) DEFAULT '0',
  `datang_dengan` varchar(50) DEFAULT NULL,
  `alasan_berobat` varchar(40) NOT NULL,
  `asal_rujukan` varchar(100) DEFAULT NULL,
  `no_rujukan` varchar(20) DEFAULT NULL,
  `kecelakaan` varchar(50) NOT NULL,
  `diagnosa` varchar(50) NOT NULL,
  `kelas_pasien` varchar(10) DEFAULT NULL,
  `cara_bayar` varchar(50) DEFAULT NULL,
  `id_poli` varchar(5) DEFAULT NULL,
  `kd_ruang` varchar(10) DEFAULT NULL,
  `biayadaftar` int(11) DEFAULT '0',
  `nama_penjamin` varchar(100) DEFAULT NULL,
  `hubungan` varchar(100) DEFAULT NULL,
  `vtot` int(11) DEFAULT '0',
  `status` char(1) DEFAULT '0',
  `tgl_pulang` date DEFAULT NULL,
  `ket_pulang` varchar(50) DEFAULT NULL,
  `no_sep` varchar(20) DEFAULT NULL,
  `xupdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `xuser` varchar(100) DEFAULT NULL,
  `xterminal` varchar(100) DEFAULT NULL,
  `karcis_bebas` varchar(30) NOT NULL,
  `lunas_karcis` date NOT NULL DEFAULT '0000-00-00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `daftar_ulang_ird` (`no_register`, `no_medrec`, `tgl_kunjungan`, `ublnrj`, `uharirj`, `umurrj`, `datang_dengan`, `alasan_berobat`, `asal_rujukan`, `no_rujukan`, `kecelakaan`, `diagnosa`, `kelas_pasien`, `cara_bayar`, `id_poli`, `kd_ruang`, `biayadaftar`, `nama_penjamin`, `hubungan`, `vtot`, `status`, `tgl_pulang`, `ket_pulang`, `no_sep`, `xupdate`, `xuser`, `xterminal`, `karcis_bebas`, `lunas_karcis`) VALUES
('RD16000001', '0000000001', '2016-03-03 03:42:48', 21, 11, 21, 'ttg', 'sakit', 'tasik', 'PSKM12345', 'parah', 'parah', 'VIP', 'Cash', '2', 'mealti', 2000000, 'asep solihin', 'Pk_kant', NULL, '0', NULL, NULL, 's12345', '2016-03-03 13:54:38', 'asep rizal', NULL, 'f', '2016-03-02');

create table provinsi(
	id varchar(2) primary key,
	nama varchar(100) not null
);

insert into provinsi values
	('11', 'ACEH'),
	('12', 'SUMATERA UTARA'),
	('13', 'SUMATERA BARAT'),
	('14', 'RIAU'),
	('15', 'JAMBI'),
	('16', 'SUMATERA SELATAN'),
	('17', 'BENGKULU'),
	('18', 'LAMPUNG'),
	('19', 'KEPULAUAN BANGKA BELITUNG'),
	('21', 'KEPULAUAN RIAU'),
	('31', 'DKI JAKARTA'),
	('32', 'JAWA BARAT'),
	('33', 'JAWA TENGAH'),
	('34', 'DI YOGYAKARTA'),
	('35', 'JAWA TIMUR'),
	('36', 'BANTEN'),
	('51', 'BALI'),
	('52', 'NUSA TENGGARA BARAT'),
	('53', 'NUSA TENGGARA TIMUR'),
	('61', 'KALIMANTAN BARAT'),
	('62', 'KALIMANTAN TENGAH'),
	('63', 'KALIMANTAN SELATAN'),
	('64', 'KALIMANTAN TIMUR'),
	('65', 'KALIMANTAN UTARA'),
	('71', 'SULAWESI UTARA'),
	('72', 'SULAWESI TENGAH'),
	('73', 'SULAWESI SELATAN'),
	('74', 'SULAWESI TENGGARA'),
	('75', 'GORONTALO'),
	('76', 'SULAWESI BARAT'),
	('81', 'MALUKU'),
	('82', 'MALUKU UTARA'),
	('91', 'PAPUA BARAT'),
	('94', 'PAPUA');
