create table irna_antrian (
	noreservasi				varchar(20) primary key,
	ruangpilih				varchar(10),
	
	no_cm					varchar(10),
	tglreserv				date,
	bed						int,
	confirm					char(1),
	lewat					varchar(7),
	batal					char(1),
	kelas					varchar(7),
	poliasal				varchar(50),
	dokter					varchar(10),
	diagnosa				varchar(100),
	tglrencanamasuk			date,
	tglsprawat				date,
	prioritas				varchar(20),
	statusantrian			char(1),
	bed_approve				varchar(10),
	tgl_approve				date,
	jam_approve				varchar(5),
	user_approve			varchar(25),
	tgl_finish				date,
	jam_finis				varchar(5),
	user_finish				varchar(25),
	no_register				varchar(10),
	keterangan				varchar(50),
	kelas_approve			varchar(7),
	ruang_approve			varchar(10),
	tppri					varchar(30),
	telp					varchar(30),
	hp						varchar(30),
	id_poli					varchar(4),
	id_dokter				varchar(10),
	no_register_asal		varchar(10),
	rujukan					varchar(30),
	alasan_batal			varchar(50),
	infeksi					char(1),
	pilihan_prioritas		varchar(20),
	
	CONSTRAINT fk_ruangpilih FOREIGN KEY (ruangpilih) REFERENCES ruang(idrg) ON DELETE CASCADE
);

create table pasien_irj(
	no_reg					varchar(11) primary key,
	
	no_cm					varchar(11),
	nama					varchar(30),
	jenis_kelamin			char(1),
	tanggal_lahir			date,
	telp					varchar(15),
	hp						varchar(15),
	id_dokter				varchar(11),
	dokter					varchar(30),
	diagnosa				varchar(50),
	id_poli					varchar(10),
	poliasal				varchar(50)
);
insert into pasien_irj values('RJ00000001', '0000000001', 'Asep Mulyadi', 'L', '1993-08-24', '(021) 234567', '085624652525', 'DK00000001', 'Mila Pradini', 'Penyakit Maag!', 'BH01', 'Klinik Mata Terpadu');
insert into pasien_irj values('RJ00000002', '0000000002', 'Aksan Maulana', 'L', '1993-03-24', '(021) 234568', '085624652536', 'DK00000002', 'Ahmad Ramdani', 'Penyakit Kulit!', 'BH02', 'Klini Kaki Terpadu');
insert into pasien_irj values('RJ00000003', '0000000003', 'Iip', 'L', '1993-05-24', '(021) 234569', '085624652547', 'DK00000003', 'Tommy Putra', 'Penyakit Flu!', 'BH03', 'Klinik Hati Terpadu');

create table pasien_ird(
	no_reg					varchar(11) primary key,
	
	no_cm					varchar(11),
	nama					varchar(30),
	jenis_kelamin			char(1),
	tanggal_lahir			date,
	telp					varchar(15),
	hp						varchar(15),
	id_dokter				varchar(11),
	dokter					varchar(30),
	diagnosa				varchar(50),
	id_poli					varchar(10),
	poliasal				varchar(50)
);
insert into pasien_ird values('RD00000001', '0000000001', 'Asep Mulyadi', 'L', '1993-08-24', '(021) 234567', '085624652525', 'DK00000001', 'Mila Pradini', 'Penyakit Maag!', 'BH01', 'Klinik Mata Terpadu');
insert into pasien_ird values('RD00000002', '0000000002', 'Aksan Maulana', 'L', '1993-03-24', '(021) 234568', '085624652536', 'DK00000002', 'Ahmad Ramdani', 'Penyakit Kulit!', 'BH01', 'Klinik Mata Terpadu');
insert into pasien_ird values('RD00000003', '0000000003', 'Iip', 'L', '1993-05-24', '(021) 234569', '085624652547', 'DK00000003', 'Tommy Putra', 'Penyakit Flu!', 'BH01', 'Klinik Mata Terpadu');

create table pasien_iri(
	no_ipd					varchar(10) primary key,
	idrg					varchar(3),
	
	tgldaftarri				date,
	no_cm					varchar(10),
	noregasal				varchar(10),
	id_smf					varchar(4),
	procmasuk				varchar(3),
	carabayar				varchar(15),
	umurri					int(3),
	ublniri					int(2),
	uhariiri				int(2),
	tgl_masuk				date,
	tgl_keluar				date,
	triwulan				int(1),
	klsiri					varchar(7),
	nopembayarri			varchar(30),
	id_kontraktor			varchar(3),
	nmpembayatri			varchar(30),
	ketpembayarri			varchar(15),
	golpembayarri			varchar(5),
	nmpjawabri				varchar(30),
	alamatpjawabri			varchar(75),
	kartuidpjawab			varchar(6),
	noidpjawab				varchar(20),
	id_dokter				varchar(11),
	kesimpulandr			varchar(2000),
	anamnesa				varchar(100),
	drpengirim				varchar(30),
	drkonsulen				varchar(30),
	innoso					char(1),
	norakiri				varchar(10),
	jatahklsiri				varchar(7),
	carapulang				varchar(15),
	keadaanpulang			varchar(20),
	penyebabpenyakit		varchar(6),
	pokumur					varchar(10),
	flagpoli				char(1),
	nama					varchar(30),
	norekom					char(7),
	modbayarri				varchar(15),
	nokkredit				varchar(20),
	nofaktur				varchar(12),
	totaldpri				int(16),
	totalbiaya				int(16),
	totalcshare				int(16),
	totaldijamin			int(16),
	totalsubsidi			int(16),
	totalselisih			int(16),
	totalbebas				int(16),
	totalbyrpenjamin		int(16),
	nokws					char(10),
	nokwfinal				char(10),
	noslipbank				char(10),
	lunas					char(1),
	tgl_lunas				date,
	oprtrlunas				varchar(15),
	xuser					varchar(15),
	xupdate					date,
	xterminal				varchar(15),
	naikkls					varchar(7),
	bed						varchar(7),
	jlhcicilan				int(16),
	jlhbyrpasien			int(16),
	jlhbypaketyan			int(12),
	jlhreturum				int(14),
	pulang					char(1),
	totalpaket				int(16),
	totalluarpaket			int(16),
	lnspasien				char(1),
	lnspenjamin				char(1),
	bylabswasta				int(14),
	nosjp					varchar(30),
	nosetoran_b				varchar(10),
	newborn					char(1),
	verif					char(1),
	veriftime				date,
	verifuser				varchar(15),
	blacklist				char(1),
	lnspjamintime			date,
	lnsjaminop				varchar(15),
	lnsjaminsrt				varchar(30),
	hubpjawabri				varchar(10),
	pilihdr					char(1),
	jnskebijakan			char(4),
	batal					char(1),
	byobat					int(14),
	nosrtaskes				varchar(20),
	nosrtpers				varchar(20),
	fkomum					char(1),
	tgltagihan				date,
	totaljasar				int(14),
	totaljasars				int(14),
	totaljasop				int(14),
	subsidijasar			int(14),
	subsidijasars			int(14),
	subsidijasop			int(14),
	tgltransaksi			date,
	xcarabayar				varchar(15),
	pemfisik				varchar(50),
	pngobatan				varchar(50),
	prognosis				varchar(50),
	lanjutan				varchar(50),
	anjuran					varchar(50),
	dtime					date,
	novoucher_pp_kasjamin	varchar(10),
	novoucher_pp_subsidi	varchar(10),
	noipdlama				varchar(9),
	notlppjawab				varchar(20),
	lamabaru				char(4),
	rawatke					int(3),
	brtlahir				int,
	pjglahir				int,
	keadaaanlhr				varchar(20),
	nmayah					varchar(30),
	penolong				varchar(30),
	diagmasuk				varchar(6),
	tglvoucher_pp_kasjamin	date,
	tglvoucher_pp_subsidi	date,
	anamakwitansi			varchar(100),
	dokter					varchar(11),
	catatan					varchar(10),
	nokwitagihan			varchar(15),
	ket_tagihan				varchar(50),
	tgl_bayar_tagihan		date,
	tgl_cetak_bon			date,
	tgl_lunas_pers			date,
	nokwlunaspers			varchar(12),
	ketlunaspers			varchar(50),
	rsmhpers				int,
	obatpers				int,
	labswastapers			int,
	bebaspers				int(12),
	rubahdata				date,
	tglbatal				date,
	userbatal				varchar(25),
	novoucher_p_bayar		varchar(10),
	tglvoucher_p_bayar		date,
	usercoucher_p_bayar		varchar(55),
	novoucher_bebaspers		varchar(10),
	tglvoucher_bebaspers	date,
	totalbiayadrg			int(15),
	biayaalat				int(15),
	verifjamkesmas			char(1),
	uverifjamkesmas			varchar(20),
	wverifjamkesmas			date,
	tgl_bebas_umu			date,
	tgl_bebas_perusahaan	date,
	penghpusan_piutang		int(15),
	tgl_penghapusan			date,
	bebas_umum				int(12),
	posjasadokter			date,
	jlhcicilpers			int(20),
	noskp					varchar(23),
	vtot					char(1),
	ketpiutang				char(30),
	flag_jasa				char(1),
	no_sep					varchar(20),
	proses_reservasi		char(1),
	ruang_reservasi			varchar(10),
	klas_reservasi			varchar(10),
	
	CONSTRAINT fk_idrg_pasien_iri FOREIGN KEY (idrg) REFERENCES ruang(idrg) ON DELETE CASCADE
);

create table ruang_iri(
	idrgiri					int auto_increment primary key,
	no_ipd					char(10),
	idrg					varchar(3),
	kelas					varchar(7),
	tglmasukrg				date,
	
	bed						varchar(9),
	nomederec				char(10),
	statmasukrg				varchar(8),
	tglkeluarrg				date,
	statkeluarrg			varchar(20),
	hrawatrg				int(3),
	jasarrg					int(14),
	dijaminrg				int(12),
	csharerg				int(12),
	selisihrg				int(12),
	subsidirg				int(12),
	pokaskes				varchar(12),
	id_dokter				varchar(11),
	naikkls					varchar(7),
	nosetoran_a				varchar(10),
	nosetoran_b				varchar(10),
	nosetoran_c				varchar(10),
	xuser					varchar(15),
	xupdate					date,
	xterminal				varchar(15),
	verif					char(1),
	veriftime				date,
	verifuser				varchar(15),
	byrpenjamin				int(12),
	tumumrg					int(14),
	novoucher_pdp			varchar(10),
	tglvoucher_pdp			date,
	jasapelrg				int(12),
	jasatotrg				int(12),
	jasarsrg				int(12),
	jasaoprg				int(12),
	novoucher				varchar(10),
	tglvoucher				date,
	novoucher_pers			varchar(10),
	tglvoucher_pers			date,
	vtot					char(1),
	
	CONSTRAINT fk_no_ipd FOREIGN KEY (no_ipd) REFERENCES pasien_iri(no_ipd) ON DELETE CASCADE,
	CONSTRAINT fk_idrg_ruang_iri FOREIGN KEY (idrg) REFERENCES ruang(idrg) ON DELETE CASCADE
);

create table irna_sliptindakan(
	noslipt					varchar(12) primary key,
	
	tglslipt				date,
	tglrealt				date,
	byumum					int(14),
	bydijamin				int(14),
	bycshare				int(14),
	bypaket					int(14),
	kelompok				varchar(5),
	dokter					varchar(11),
	no_ipd					char(10),
	idrg					char(3),
	
	CONSTRAINT fk_idrg_irna_sliptindakan FOREIGN KEY (idrg) REFERENCES ruang(idrg) ON DELETE CASCADE,
	CONSTRAINT fk_no_ipd_irna_sliptindakan FOREIGN KEY (no_ipd) REFERENCES pasien_iri(no_ipd) ON DELETE CASCADE
);

create table pelayanan_iri(
	tgl_layanan				date,
	id_jns_layanan			char(6),
	no_ipd					char(10),
	idrg					varchar(3),
	kelas					varchar(7),
	noslipt					varchar(12),
	
	nomederec				char(10),
	qtyyanri				int(3),
	jasarinap				int(4),
	jasarsinap				int(14),
	jasaopinap				int(14),
	tumuminap				int(16),
	dijamininap				int(20),
	cshareinap				int(14),
	selisihinap				int(12),
	subsidiinap				int(12),
	pokaskes				varchar(12),
	kategori				varchar(9),
	idoprtr					varchar(11),
	pokoprtr				varchar(7),
	nosetoran_b				varchar(10),
	nosetoran_c				varchar(10),
	xuser					varchar(15),
	xupdate					date,
	xterminal				varchar(15),
	verif					char(1),
	veriftime				date,
	verifuser				varchar(15),
	jasaaneinap				int(14),
	novoucher_pdp			varchar(10),
	tglvoucher				date,
	novoucher_koreksi		varchar(10),
	tglvoucherkoreksi		date,
	xmodif					date,
	batal					char(1),
	tglvoucher_pdp			date,
	penurang_op				char(1),
	pengurang_op			char(1),
	kurang_dr				char(1),
	novoucher				varchar(10),
	tglentry				date,
	novoucher_pers			varchar(10),
	tglvoucher_pers			date,
	vtot					char(1),
	nomor					int,
	
	CONSTRAINT fk_no_ipd_pelayanan_iri FOREIGN KEY (no_ipd) REFERENCES pasien_iri(no_ipd) ON DELETE CASCADE,
	CONSTRAINT fk_idrg_pelayanan_iri FOREIGN KEY (idrg) REFERENCES ruang(idrg) ON DELETE CASCADE,
	CONSTRAINT fk_noslipt_pelayanan_iri FOREIGN KEY (noslipt) REFERENCES irna_sliptindakan(noslipt) ON DELETE CASCADE
);

create table ruang(
	idrg					varchar(3) primary key,
	
	nmruang					varchar(30),
	pokruang				varchar(20),
	pokrgtarif				varchar(25),
	tipebt					char(1),
	kodebt					varchar(10),
	id_dept					varchar(4),
	koderg					varchar(5),
	idf						varchar(6)
);
insert into ruang(idrg, nmruang, koderg) value('104', 'Pav. Lematang Indah 1', 'II');
insert into ruang(idrg, nmruang, koderg) value('105', 'Pav. Lematang Indah 2', 'II');
insert into ruang(idrg, nmruang, koderg) value('106', 'Pav. Musi Elok (Lantai 2)', 'II');
insert into ruang(idrg, nmruang, koderg) value('107', 'Non Aktif-Pav.Melati (MJD 511)', 'II');
insert into ruang(idrg, nmruang, koderg) value('201', 'Obgyn B (Anggrek Lt. 1)', 'II');
insert into ruang(idrg, nmruang, koderg) value('202', 'Bayi (Anggrek Lt.1 & 2)', 'II');
insert into ruang(idrg, nmruang, koderg) value('203', 'Obgyn C (Anggrek Lt. 2)', 'II');
insert into ruang(idrg, nmruang, koderg) value('301', 'Neonatus (Kemuning Lt.2)', 'II');
insert into ruang(idrg, nmruang, koderg) value('303', 'Non Aktif-NICU (MJD 603)', 'II');
insert into ruang(idrg, nmruang, koderg) value('304', 'Non Aktif PICU (MJD 604)', 'II');
insert into ruang(idrg, nmruang, koderg) value('401', 'Kenanga A (RKB A)', 'II');
insert into ruang(idrg, nmruang, koderg) value('108', 'Intermediate', 'II');
